/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Vrml3dPaonel.java
 *
 * Created on 05/06/2010, 16:36:15
 */
package vrml3d.GUI;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.media.j3d.BoundingBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import vrml3d.core.My_VRML;
import vrml3d.core.Plug;

/**
 *
 * @author Marcel
 */
public class Vrml3dPainel extends javax.swing.JFrame {

    ArrayList lits ;
    int num;
    My_VRML core;
    JLabel[] plug;
    JPanel[] status;

    /** Creates new form Vrml3dPaonel */
    public Vrml3dPainel(int num, My_VRML core,String[] deriv) {
        this.setTitle("Painel de Verificação de Plugs");
        this.setVisible(true);
        this.core = core;
        plug = new JLabel[num];
        status = new JPanel[num];
        initComponents();
        int xi = 8, yNext = 22;
        lits = core.getApp().getListPlugs();
        for (int i = 0; i < num; i++) {
            plug[i] = new JLabel();
            yNext = 22 + (25 * i);
            plug[i].setLocation(xi, yNext);
            plug[i].setSize(90, 35);
            plug[i].setText(deriv[i]);
            plug[i].setVisible(true);
            jPanel1.add(plug[i]);
        }
        xi = 94;
        for (int i = 0; i < num; i++) {
            status[i] = new JPanel();
            yNext = 24 + (25 * i);
            status[i].setLocation(xi, yNext);
            status[i].setSize(20, 20);
            status[i].setVisible(true);
            status[i].setBackground(new Color(255, 0, 0));
            jPanel1.add(status[i]);
        }


        Timer timer = new Timer(100, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                Limpa();
                Verifica();
                Pinta();

            }
        });

        timer.start();

    }

    public void Limpa() {
        
        for (int j = 0; j < status.length; j++) {
            status[j].setBackground(new Color(255, 0, 0));
        }
        for(int i=0;i<lits.size();i++){
        ((Plug)lits.get(i)).setLocal(-1);
        }
    }

    public void Verifica() {

        ArrayList lits = core.getApp().getListPlugs();
        ArrayList posicoes = core.getApp().getPosicoes();

        for (int i = 0; i < lits.size(); i++) {
            Plug temp = (Plug) lits.get(i);            
            for (int k = 0; k < posicoes.size(); k++) {
                if (((BoundingBox) (posicoes.get(k))).intersect(temp.getXYZ())) {
                    temp.setLocal(k);
                    
                }
            }

        }
    }

    public void Pinta(){

                for (int l = 0; l < lits.size(); l++) {
                    Plug temp = (Plug) lits.get(l);
                    if (temp.getLocal() != -1) {
                        status[temp.getLocal()].setBackground(new Color(0, 255, 18));
                    }
                }
    }

    /** This method is called from within the constructor to
     * initialize the form.;
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        
        jPanel1.setName("jPanel1"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
